apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  service_port: {{ .Values.config.port | quote }}
  service_hostname: {{ .Values.config.hostname | quote }}
  service_log_level: {{ .Values.config.logLevel | quote }}
  service_req_timeout: {{ .Values.config.reqTimeout | quote }}
