apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background  # Avoid orphaned childs
  annotations:
    argocd.argoproj.io/sync-wave: "1" # For dependencies ordering
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: ghcr.io/prometheus-community/charts
    targetRevision: 80.6.0
    helm:
      values: |
        alertmanager:
          alertmanagerSpec:
            replicas: 1
        grafana:
          replicas: 1
        prometheus:
          prometheusSpec:
            replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:  # Enable Continuos Deployment (instead of Continuos Delivery)
      prune: true # Delete corresponding K8s resources if removed from Git
      selfHeal: true  # Rollback manual changes (avoid config drift)
    retry:  # Handle transient failures
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Avoid the 262,144-byte annotation size limit
