name: CICD pipeline
on: workflow_dispatch

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            webserver
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'webserver/go.mod'
          cache-dependency-path: 'webserver/go.sum'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          working-directory: webserver

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            webserver
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'webserver/go.mod'
          cache-dependency-path: 'webserver/go.sum'
          cache: true
      - name: Run Go test coverage
        working-directory: webserver
        run: go test -cover ./...

  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            webserver
      - name: Scan repository for vulnerabilities (generate SBOM)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: 'webserver'
          trivy-config: trivy.yaml
          output: '${{ github.workspace }}/dependency-results.sbom.json'
          format: 'github'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

  build-scan-push-image:
    needs: [lint-and-format, test, scan-repo]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            webserver
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Container image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/testdotcom/webserver
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build container image
        uses: docker/bake-action@v6
        id: build
        with:
          push: false
          load: true
          workdir: webserver
          source: "{{defaultContext}}:webserver"
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-tags }}
          targets: build
          set: |
            *.output=type=docker
      - name: Scan container image for vulnerabilities
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'ghcr.io/testdotcom/webserver:latest'
          trivy-config: trivy.yaml
          scan-type: 'image'
          format: 'sarif'
          output: '${{ github.workspace }}/trivy-results.sarif'
      - name: Upload SARIF scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: '${{ github.workspace }}/trivy-results.sarif'
      - name: Push container image
        if: success()
        uses: docker/bake-action@v6
        with:
          push: true
          workdir: webserver
          source: "{{defaultContext}}:webserver"
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-tags }}
          targets: build
