name: CICD pipeline
on: workflow_dispatch

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            webserver
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'webserver/go.mod'
          cache-dependency-path: 'webserver/go.sum'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          working-directory: webserver
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            webserver
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'webserver/go.mod'
          cache-dependency-path: 'webserver/go.sum'
          cache: true
      - name: Run Go test coverage
        working-directory: webserver
        run: go test -cover ./...
  build-image:
    needs: [lint-and-format, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            webserver
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Container image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/testdotcom/webserver
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
          workdir: webserver
          source: "{{defaultContext}}"
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-tags }}
          targets: build
